### PR TITLE
#79 Move auto-login cookie params to component config parameters

### PR DESCRIPTION
**Pull request by olegbaturin**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌
| Fixed issues  | #79

### CODE REVIEW

**Comment by olegbaturin** [comment]
Is php 7.4 support required for this package?

**Comment by vjik** [comment]
> Is php 7.4 support required for this package?

No. If you want raise PHP version to 8.0, please, create this in separate PR.

**Comment by rustamwin** [comment]
> No. If you want to raise PHP version to 8.0, please, create this in separate PR.

Here is https://github.com/yiisoft/user/pull/58

**Comment by olegbaturin** [comment]
> > Is php 7.4 support required for this package?
> 
> No. If you want to raise PHP version to 8.0, please, create this in separate PR.

https://github.com/yiisoft/user/pull/78

This PR already requires to raise min php ver to 8.0.

**Comment by vjik** [comment]
@olegbaturin PHP version raised in master branch. You can merge master to your branch.

**Pull request closed without merging**
